serverName: SleepingServer, waiting for his prince...
serverPort: 25565
bedrockPort: 19132
maxPlayers: 20
loginMessage: ...Waking server up, come back in a minute...
serverOnlineMode: true
webPort: 0
startMinecraft: 1
minecraftCommand: java -jar spigot.jar nogui
